# yaml-language-server: $schema=https://json.schemastore.org/github-workflow

name: Deploy Assets
on:
  push:
    branches:
      - deploy

permissions: {}

jobs:
  wordpress:
    name: WordPress.org
    permissions:
      contents: read
    uses: johnbillion/plugin-infrastructure/.github/workflows/reusable-deploy-assets.yml@trunk
    with:
      plugin: user-switching
      readme: readme.txt
      username: johnbillion
    secrets:
      WPORG_SVN_PASSWORD: ${{ secrets.WPORG_SVN_PASSWORD }}
